using System.Collections.Concurrent;
using System.IO;
using System.Security.Cryptography;
using System.Text.Json;
using System.Text.Json.Serialization;

using AiUsageDashboard.Core.Models;
using AiUsageDashboard.Core.Persistence;

namespace AiUsageDashboard.App.Persistence;

public sealed class JsonAccountProfileStore : IAccountProfileStore
{
	private sealed record PortableImportLoadedFileState(
		bool FileExisted,
		string? Fingerprint);

	private enum BackupValidationStatus
	{
		Available,
		Blocked,
		FutureVersion,
		Oversized,
		Unavailable
	}

	private sealed record AccountDocument(
		Guid Id,
		ProviderKind? Provider,
		string? DisplayName,
		bool? IsEnabled,
		string? ProviderAccountIdentity = null,
		bool? HasAcceptedClaudeQuotaRisk = null,
		bool? ShowSubscriptionContext = null);

	private sealed record SettingsDocument(
		int SchemaVersion,
		List<AccountDocument?>? Accounts);

	private sealed record ParsedSettingsDocument(
		int SchemaVersion,
		IReadOnlyList<AccountProfile>? Accounts);

	private sealed class SettingsFileTooLargeException : IOException
	{
		public SettingsFileTooLargeException()
			: base("帳號設定檔不可超過 1 MB。")
		{
		}
	}

	private const string BackupFileSuffix = ".bak";
	private const int AutoGeneratedDisplayNameSchemaVersion = 2;
	private const int AutoGeneratedDisplayNameLastSchemaVersion = 4;
	private const int ClaudeQuotaRiskSchemaVersion = 4;
	private const int CurrentSchemaVersion = 7;
	private const int LegacySchemaVersion = 1;
	private const int MaximumAccountCount = 256;
	private const int MaximumDisplayNameLength = 80;
	private const int MaximumSettingsFileSize = 1024 * 1024;
	private const string ManagedPathDescription = "The account profile path";
	private const int SubscriptionContextSchemaVersion = 7;
	private static readonly ConcurrentDictionary<string, SemaphoreSlim> FileGates =
		new(StringComparer.OrdinalIgnoreCase);
	private static readonly JsonSerializerOptions SerializerOptions = CreateSerializerOptions();
	private readonly SemaphoreSlim _fileGate;
	private readonly string _filePath;
	private readonly object _portableImportStateSync = new();
	private bool _canSave = true;
	private bool _isInitialized;
	private bool _loadedFileExisted;
	private string? _loadedFileFingerprint;
	private PortableImportLoadedFileState? _portableImportLoadedFileState;
	private readonly PortableSettingsImportWriteTracker?
		_portableSettingsImportWriteTracker;
	private readonly Action<string, string, Exception?> _reportDiagnostic;
	private string? _saveBlockedMessage;

	public string FilePath => _filePath;

	private string BackupFilePath => $"{_filePath}{BackupFileSuffix}";

	public JsonAccountProfileStore(string filePath)
		: this(filePath, portableSettingsImportWriteTracker: null)
	{
	}

	internal JsonAccountProfileStore(
		string filePath,
		PortableSettingsImportWriteTracker?
			portableSettingsImportWriteTracker,
		Action<string, string, Exception?>? reportDiagnostic = null)
	{
		ArgumentException.ThrowIfNullOrWhiteSpace(filePath);
		_filePath = Path.GetFullPath(filePath);
		_fileGate = FileGates.GetOrAdd(_filePath, _ => new SemaphoreSlim(1, 1));
		_portableSettingsImportWriteTracker =
			portableSettingsImportWriteTracker;
		_reportDiagnostic = reportDiagnostic ?? ((_, _, _) => { });
	}

	public async Task<AccountProfileLoadResult> LoadAsync(
		CancellationToken cancellationToken = default)
	{
		await _fileGate.WaitAsync(cancellationToken);

		try
		{
			return await LoadCoreAsync(cancellationToken);
		}
		finally
		{
			_fileGate.Release();
		}
	}

	public async Task SaveAsync(
		IReadOnlyList<AccountProfile> accounts,
		CancellationToken cancellationToken = default)
	{
		ArgumentNullException.ThrowIfNull(accounts);
		await _fileGate.WaitAsync(cancellationToken);

		try
		{
			if (!_isInitialized)
			{
				AccountProfileLoadResult loadResult = await LoadCoreAsync(cancellationToken);

				if (!loadResult.CanSave)
				{
					throw new AccountProfileStoreException(
						loadResult.Message ?? "帳號設定目前不可寫入。");
				}
			}

			if (!_canSave)
			{
				throw new AccountProfileStoreException(
					_saveBlockedMessage ?? "帳號設定目前不可寫入。");
			}

			SettingsDocument document = CreateDocument(accounts);
			await VerifyFileHasNotChangedAsync(cancellationToken);
			await VerifyBackupCanBeReplacedAsync(cancellationToken);
			string fingerprint = await SaveDocumentAsync(document, cancellationToken);
			SetLoadedFileState(fileExisted: true, fingerprint: fingerprint);
		}
		catch (OperationCanceledException)
		{
			throw;
		}
		catch (AccountProfileStoreException)
		{
			throw;
		}
		catch (ArgumentException)
		{
			throw;
		}
		catch (Exception exception) when (
			(exception is IOException) ||
			(exception is UnauthorizedAccessException) ||
			(exception is InvalidDataException) ||
			(exception is NotSupportedException))
		{
			throw new AccountProfileStoreException(
				"帳號設定無法儲存；原設定檔未變更。",
				exception);
		}
		finally
		{
			_fileGate.Release();
		}
	}

	internal async Task BeginPortableImportTransactionAsync(
		CancellationToken cancellationToken = default)
	{
		await _fileGate.WaitAsync(cancellationToken).ConfigureAwait(false);

		try
		{
			lock (_portableImportStateSync)
			{
				_portableImportLoadedFileState = _isInitialized
					? new PortableImportLoadedFileState(
						_loadedFileExisted,
						_loadedFileFingerprint)
					: null;
			}
		}
		finally
		{
			_fileGate.Release();
		}
	}

	internal async Task SynchronizeLoadedFileStateAfterExternalRestoreAsync(
		CancellationToken cancellationToken = default)
	{
		await _fileGate.WaitAsync(cancellationToken).ConfigureAwait(false);

		try
		{
			PortableImportLoadedFileState? baselineState;

			lock (_portableImportStateSync)
			{
				baselineState = _portableImportLoadedFileState;
			}

			// Startup recovery precedes LoadAsync. During an in-session rollback,
			// restore the loaded state that matched the UI before the transaction.
			// A conditional rollback may deliberately preserve a later external
			// file; adopting that file's fingerprint here would let the unchanged UI
			// overwrite it on its next save without triggering stale-writer defense.
			if (!_isInitialized ||
				(baselineState is null) ||
				((_loadedFileExisted == baselineState.FileExisted) &&
					string.Equals(
						_loadedFileFingerprint,
						baselineState.Fingerprint,
						StringComparison.Ordinal)))
			{
				return;
			}

			SetLoadedFileState(
				baselineState.FileExisted,
				baselineState.Fingerprint);
		}
		finally
		{
			_fileGate.Release();
		}
	}

	internal void CompletePortableImportTransaction()
	{
		lock (_portableImportStateSync)
		{
			_portableImportLoadedFileState = null;
		}
	}

	private static SettingsDocument CreateDocument(
		IReadOnlyList<AccountProfile> accounts)
	{
		if (accounts.Count > MaximumAccountCount)
		{
			throw new ArgumentException(
				$"帳號數量不可超過 {MaximumAccountCount} 個。",
				nameof(accounts));
		}

		HashSet<Guid> accountIds = new();
		Dictionary<ProviderKind, HashSet<string>> providerAccountIdentities = new();
		List<AccountDocument?> accountDocuments = new(accounts.Count);

		foreach (AccountProfile account in accounts)
		{
			if (account.Id == Guid.Empty)
			{
				throw new ArgumentException("帳號資料不可為空。", nameof(accounts));
			}

			if (!accountIds.Add(account.Id))
			{
				throw new ArgumentException("帳號不可重複。", nameof(accounts));
			}

			if (!Enum.IsDefined(typeof(ProviderKind), account.Provider))
			{
				throw new ArgumentException("帳號包含不支援的服務。", nameof(accounts));
			}

			string displayName = NormalizeDisplayName(account.DisplayName, nameof(accounts));
			string? providerAccountIdentity = NormalizeProviderAccountIdentity(
				account.Provider,
				account.ProviderAccountIdentity,
				nameof(accounts));
			EnsureUniqueProviderAccountIdentity(
				providerAccountIdentities,
				account.Provider,
				providerAccountIdentity,
				nameof(accounts));
			accountDocuments.Add(new AccountDocument(
				account.Id,
				account.Provider,
				displayName,
				account.IsEnabled,
				providerAccountIdentity,
				account.Provider == ProviderKind.Claude &&
					account.HasAcceptedClaudeQuotaRisk,
				account.ShowSubscriptionContext));
		}

		return new SettingsDocument(CurrentSchemaVersion, accountDocuments);
	}

	private static JsonSerializerOptions CreateSerializerOptions()
	{
		JsonSerializerOptions options = new()
		{
			MaxDepth = 16,
			DefaultIgnoreCondition = JsonIgnoreCondition.WhenWritingNull,
			PropertyNameCaseInsensitive = false,
			PropertyNamingPolicy = JsonNamingPolicy.CamelCase,
			UnmappedMemberHandling = JsonUnmappedMemberHandling.Disallow,
			WriteIndented = true
		};
		options.Converters.Add(new JsonStringEnumConverter(
			namingPolicy: null,
			allowIntegerValues: false));
		return options;
	}

	private static string ComputeFingerprint(byte[] fileContents)
	{
		return Convert.ToHexString(SHA256.HashData(fileContents));
	}

	private static Task CreateDirectoryAsync(
		string directoryPath,
		CancellationToken cancellationToken)
	{
		cancellationToken.ThrowIfCancellationRequested();
		return Task.Run(
			() => ManagedFilePathGuard.CreateDirectoryAndEnsureSafe(
				directoryPath,
				ManagedPathDescription),
			cancellationToken);
	}

	private static Task<bool> FileExistsAsync(
		string filePath,
		CancellationToken cancellationToken)
	{
		cancellationToken.ThrowIfCancellationRequested();
		return Task.Run(
			() => FileExistsSafely(filePath),
			cancellationToken);
	}

	private static bool FileExistsSafely(string filePath)
	{
		ManagedFilePathGuard.EnsureExistingFilePathIsSafe(
			filePath,
			ManagedPathDescription);
		return File.Exists(filePath);
	}

	private static byte[] ReadSettingsFile(string filePath)
	{
		ManagedFilePathGuard.EnsureExistingFilePathIsSafe(
			filePath,
			ManagedPathDescription);
		using FileStream stream = new(
			filePath,
			FileMode.Open,
			FileAccess.Read,
			FileShare.Read,
			bufferSize: 4096,
			FileOptions.SequentialScan);
		int fileLength = ValidateSettingsFileLength(stream.Length);
		byte[] fileContents = GC.AllocateUninitializedArray<byte>(fileLength);
		stream.ReadExactly(fileContents);
		return fileContents;
	}

	private static Task<byte[]> ReadSettingsFileAsync(
		string filePath,
		CancellationToken cancellationToken)
	{
		cancellationToken.ThrowIfCancellationRequested();
		return Task.Run(
			async () =>
			{
				ManagedFilePathGuard.EnsureExistingFilePathIsSafe(
					filePath,
					ManagedPathDescription);
				await using FileStream stream = new(
					filePath,
					FileMode.Open,
					FileAccess.Read,
					FileShare.Read,
					bufferSize: 4096,
					FileOptions.Asynchronous | FileOptions.SequentialScan);
				int fileLength = ValidateSettingsFileLength(stream.Length);
				byte[] fileContents =
					GC.AllocateUninitializedArray<byte>(fileLength);
				await stream.ReadExactlyAsync(fileContents, cancellationToken)
					.ConfigureAwait(false);
				return fileContents;
			},
			cancellationToken);
	}

	private static int ValidateSettingsFileLength(long fileLength)
	{
		if (fileLength > MaximumSettingsFileSize)
		{
			throw new SettingsFileTooLargeException();
		}

		return checked((int)fileLength);
	}

	private static ParsedSettingsDocument ParseSettingsDocument(byte[] fileContents)
	{
		using JsonDocument parsedDocument = JsonDocument.Parse(
			fileContents,
			new JsonDocumentOptions
			{
				MaxDepth = 16
			});

		if (parsedDocument.RootElement.ValueKind != JsonValueKind.Object)
		{
			throw new InvalidDataException("帳號設定檔根節點必須是物件。");
		}

		if (!parsedDocument.RootElement.TryGetProperty(
			"schemaVersion",
			out JsonElement schemaVersionElement) ||
			schemaVersionElement.ValueKind != JsonValueKind.Number ||
			!schemaVersionElement.TryGetInt32(out int schemaVersion))
		{
			throw new InvalidDataException("設定檔缺少 schemaVersion。");
		}

		if (schemaVersion > CurrentSchemaVersion)
		{
			return new ParsedSettingsDocument(schemaVersion, Accounts: null);
		}

		if (schemaVersion < LegacySchemaVersion)
		{
			throw new InvalidDataException("設定檔版本無效。");
		}

		if (!parsedDocument.RootElement.TryGetProperty(
				"accounts",
				out JsonElement accountsElement) ||
			(accountsElement.ValueKind != JsonValueKind.Array) ||
			(accountsElement.GetArrayLength() > MaximumAccountCount))
		{
			throw new InvalidDataException("帳號清單格式或數量無效。");
		}

		SettingsDocument? document = JsonSerializer.Deserialize<SettingsDocument>(
			fileContents,
			SerializerOptions);

		if (document is null)
		{
			throw new InvalidDataException("帳號設定檔內容不可為空。");
		}

		IReadOnlyList<AccountProfile> accounts = ReadAccounts(document);

		if (schemaVersion == LegacySchemaVersion)
		{
			accounts = accounts
				.OrderBy(account => account.Provider)
				.ThenBy(
					account => account.DisplayName,
					StringComparer.CurrentCultureIgnoreCase)
				.ToArray();
		}

		if ((schemaVersion >= AutoGeneratedDisplayNameSchemaVersion) &&
			(schemaVersion <= AutoGeneratedDisplayNameLastSchemaVersion))
		{
			accounts = accounts
				.Select(account => IsLegacyAutoGeneratedDisplayName(
					account.Provider,
					account.DisplayName)
					? account with { DisplayName = string.Empty }
					: account)
				.ToArray();
		}

		return new ParsedSettingsDocument(schemaVersion, accounts);
	}

	private static IReadOnlyList<AccountProfile> ReadAccounts(
		SettingsDocument document)
	{
		if ((document.Accounts is null) ||
			(document.Accounts.Count > MaximumAccountCount))
		{
			throw new InvalidDataException("帳號清單格式或數量無效。");
		}

		HashSet<Guid> accountIds = new();
		Dictionary<ProviderKind, HashSet<string>> providerAccountIdentities = new();
		List<AccountProfile> accounts = new(document.Accounts.Count);

		foreach (AccountDocument? account in document.Accounts)
		{
			if (account is null)
			{
				throw new InvalidDataException("帳號項目不可為空。");
			}

			if (account.Id == Guid.Empty)
			{
				throw new InvalidDataException("帳號資料不可為空。");
			}

			if (!accountIds.Add(account.Id))
			{
				throw new InvalidDataException("帳號不可重複。");
			}

			if ((account.Provider is null) ||
				!Enum.IsDefined(typeof(ProviderKind), account.Provider.Value))
			{
				throw new InvalidDataException("帳號缺少服務，或服務不受支援。");
			}

			if (account.IsEnabled is null)
			{
				throw new InvalidDataException("帳號缺少用量檢查設定。");
			}

			if ((document.SchemaVersion >= ClaudeQuotaRiskSchemaVersion) &&
				(account.HasAcceptedClaudeQuotaRisk is null))
			{
				throw new InvalidDataException(
					"帳號缺少 hasAcceptedClaudeQuotaRisk。");
			}

			if ((document.SchemaVersion >= SubscriptionContextSchemaVersion) &&
				(account.ShowSubscriptionContext is null))
			{
				throw new InvalidDataException(
					"帳號缺少 showSubscriptionContext。");
			}

			string displayName = NormalizeDisplayName(account.DisplayName, null);

			string? providerAccountIdentity = NormalizeProviderAccountIdentity(
				account.Provider.Value,
				account.ProviderAccountIdentity,
				parameterName: null);
			bool hasAcceptedClaudeQuotaRisk =
				(document.SchemaVersion >= ClaudeQuotaRiskSchemaVersion) &&
				(account.Provider.Value == ProviderKind.Claude) &&
				(account.HasAcceptedClaudeQuotaRisk == true);
			EnsureUniqueProviderAccountIdentity(
				providerAccountIdentities,
				account.Provider.Value,
				providerAccountIdentity,
				parameterName: null);
			accounts.Add(new AccountProfile(
				account.Id,
				account.Provider.Value,
				displayName,
				account.IsEnabled.Value,
				providerAccountIdentity,
				hasAcceptedClaudeQuotaRisk,
				ShowSubscriptionContext:
					document.SchemaVersion >= SubscriptionContextSchemaVersion &&
					(account.ShowSubscriptionContext == true)));
		}

		return accounts;
	}

	private static string NormalizeDisplayName(
		string? displayName,
		string? parameterName)
	{
		if (displayName is null)
		{
			if (parameterName is not null)
			{
				throw new ArgumentException("帳號顯示名稱不可為 null。", parameterName);
			}

			throw new InvalidDataException("帳號顯示名稱不可為 null。");
		}

		string normalizedDisplayName = displayName.Trim();

		if (normalizedDisplayName.Length > MaximumDisplayNameLength)
		{
			if (parameterName is not null)
			{
				throw new ArgumentException(
					$"帳號顯示名稱不可超過 {MaximumDisplayNameLength} 個字元。",
					parameterName);
			}

			throw new InvalidDataException("帳號顯示名稱過長。");
		}

		if (normalizedDisplayName.Any(char.IsControl))
		{
			if (parameterName is not null)
			{
				throw new ArgumentException(
					"帳號顯示名稱不可包含控制字元。",
					parameterName);
			}

			throw new InvalidDataException("帳號顯示名稱包含控制字元。");
		}

		return normalizedDisplayName;
	}

	private static bool IsLegacyAutoGeneratedDisplayName(
		ProviderKind provider,
		string displayName)
	{
		string providerDisplayName = provider switch
		{
			ProviderKind.Claude => "Claude",
			ProviderKind.Codex => "Codex",
			ProviderKind.Copilot => "GitHub Copilot",
			ProviderKind.Antigravity => "Antigravity",
			ProviderKind.Grok => "Grok",
			_ => throw new ArgumentOutOfRangeException(nameof(provider))
		};

		if (string.Equals(
				displayName,
				providerDisplayName,
				StringComparison.Ordinal))
		{
			return true;
		}

		string numberedPrefix = $"{providerDisplayName} ";

		if (!displayName.StartsWith(numberedPrefix, StringComparison.Ordinal))
		{
			return false;
		}

		ReadOnlySpan<char> suffix = displayName.AsSpan(numberedPrefix.Length);

		if ((suffix.Length == 0) || (suffix[0] == '0'))
		{
			return false;
		}

		foreach (char character in suffix)
		{
			if ((character < '0') || (character > '9'))
			{
				return false;
			}
		}

		return (suffix.Length > 1) || (suffix[0] >= '2');
	}

	private static void EnsureUniqueProviderAccountIdentity(
		Dictionary<ProviderKind, HashSet<string>> providerAccountIdentities,
		ProviderKind provider,
		string? providerAccountIdentity,
		string? parameterName)
	{
		if (providerAccountIdentity is null)
		{
			return;
		}

		if (!providerAccountIdentities.TryGetValue(
				provider,
				out HashSet<string>? identities))
		{
			identities = new HashSet<string>(
				ProviderAccountIdentityRules.Comparer);
			providerAccountIdentities.Add(provider, identities);
		}

		if (identities.Add(providerAccountIdentity))
		{
			return;
		}

		if (parameterName is not null)
		{
			throw new ArgumentException(
				"同一個登入帳號不可重複連接到多張帳號卡片。",
				parameterName);
		}

		throw new InvalidDataException(
			"同一個登入帳號不可重複連接到多張帳號卡片。");
	}

	private static string? NormalizeProviderAccountIdentity(
		ProviderKind provider,
		string? providerAccountIdentity,
		string? parameterName)
	{
		if (ProviderAccountIdentityRules.TryNormalize(
				providerAccountIdentity,
				out string? normalizedIdentity))
		{
			if ((provider != ProviderKind.Grok) ||
				(normalizedIdentity is null) ||
				GrokAccountBinding.TryNormalizePublicBindingIdentity(
					providerAccountIdentity,
					out normalizedIdentity))
			{
				return normalizedIdentity;
			}
		}

		if (parameterName is not null)
		{
			throw new ArgumentException(
				provider == ProviderKind.Grok
					? "Grok 帳號連接資料格式無效。"
					: "帳號資訊格式無效。",
				parameterName);
		}

		throw new InvalidDataException(
			provider == ProviderKind.Grok
				? "Grok 帳號連接資料格式無效。"
				: "帳號資訊格式無效。");
	}

	private async Task<AccountProfileLoadResult> LoadCoreAsync(
		CancellationToken cancellationToken)
	{
		_isInitialized = false;
		SetLoadedFileState(fileExisted: false, fingerprint: null);
		EnableSaving();

		string? loadedFileFingerprint = null;

		try
		{
			if (!await FileExistsAsync(_filePath, cancellationToken)
					.ConfigureAwait(false))
			{
				return await LoadMissingPrimaryAsync(cancellationToken);
			}

			byte[] fileContents = await ReadSettingsFileAsync(
				_filePath,
				cancellationToken);
			loadedFileFingerprint = ComputeFingerprint(fileContents);
			ParsedSettingsDocument document = ParseSettingsDocument(fileContents);

			if (document.SchemaVersion > CurrentSchemaVersion)
			{
				string unsupportedVersionMessage =
					"這份帳號設定由較新版本建立。為避免覆寫，目前無法編輯帳號。";
				BlockSaving(unsupportedVersionMessage);
				SetLoadedFileState(fileExisted: true, fingerprint: loadedFileFingerprint);
				_isInitialized = true;
				return new AccountProfileLoadResult(
					Array.Empty<AccountProfile>(),
					AccountProfileLoadStatus.UnsupportedVersion,
					CanSave: false,
					unsupportedVersionMessage);
			}

			BackupValidationStatus backupStatus = await TryEnsureValidatedBackupAsync(
				fileContents,
				cancellationToken);
			SetLoadedFileState(fileExisted: true, fingerprint: loadedFileFingerprint);
			_isInitialized = true;

			if (backupStatus == BackupValidationStatus.Blocked)
			{
				string blockedBackupMessage =
					"帳號設定已載入，但無法讀取備份。為避免覆寫，目前無法編輯帳號。";
				BlockSaving(blockedBackupMessage);
				return new AccountProfileLoadResult(
					document.Accounts!,
					AccountProfileLoadStatus.Loaded,
					CanSave: false,
					blockedBackupMessage);
			}

			if (backupStatus == BackupValidationStatus.FutureVersion)
			{
				string futureBackupMessage =
					"帳號設定已載入，但備份由較新版本建立。為避免覆寫，目前無法編輯帳號。";
				BlockSaving(futureBackupMessage);
				return new AccountProfileLoadResult(
					document.Accounts!,
					AccountProfileLoadStatus.Loaded,
					CanSave: false,
					futureBackupMessage);
			}

			if (backupStatus == BackupValidationStatus.Oversized)
			{
				string oversizedBackupMessage =
					"帳號設定已載入，但備份超過 1 MB。為避免覆寫，目前無法編輯帳號。";
				BlockSaving(oversizedBackupMessage);
				return new AccountProfileLoadResult(
					document.Accounts!,
					AccountProfileLoadStatus.Loaded,
					CanSave: false,
					oversizedBackupMessage);
			}

			string? backupMessage = backupStatus == BackupValidationStatus.Available
				? null
				: "帳號設定已載入，但無法建立或修復備份。目前仍可使用；請確認資料夾寫入權限。";
			return new AccountProfileLoadResult(
				document.Accounts!,
				AccountProfileLoadStatus.Loaded,
				CanSave: true,
				backupMessage);
		}
		catch (OperationCanceledException)
		{
			throw;
		}
		catch (SettingsFileTooLargeException)
		{
			string message =
				"帳號設定檔超過 1 MB。為避免耗用過多記憶體或覆寫原檔，目前無法編輯帳號。";
			BlockSaving(message);
			_isInitialized = true;
			return new AccountProfileLoadResult(
				Array.Empty<AccountProfile>(),
				AccountProfileLoadStatus.Unavailable,
				CanSave: false,
				message);
		}
		catch (Exception exception) when (
			(exception is JsonException) ||
			(exception is InvalidDataException) ||
			(exception is NotSupportedException))
		{
			return await RecoverCorruptFileAsync(
				loadedFileFingerprint,
				cancellationToken);
		}
		catch (Exception exception) when (
			(exception is IOException) ||
			(exception is UnauthorizedAccessException))
		{
			ReportDiagnostic(
				"account-profile-load",
				"stage=primary-read;result=unavailable",
				exception);
			string message = "無法讀取帳號設定檔。為避免覆寫，目前無法編輯帳號。";
			BlockSaving(message);
			_isInitialized = true;
			return new AccountProfileLoadResult(
				Array.Empty<AccountProfile>(),
				AccountProfileLoadStatus.Unavailable,
				CanSave: false,
				message);
		}
	}

	private async Task<BackupValidationStatus> TryEnsureValidatedBackupAsync(
		byte[] validatedFileContents,
		CancellationToken cancellationToken)
	{
		bool backupExists;

		try
		{
			backupExists = await FileExistsAsync(BackupFilePath, cancellationToken)
				.ConfigureAwait(false);
		}
		catch (OperationCanceledException)
		{
			throw;
		}
		catch (Exception exception) when (
			(exception is IOException) ||
			(exception is UnauthorizedAccessException))
		{
			ReportDiagnostic(
				"account-profile-load",
				"stage=backup-validation;result=unavailable",
				exception);
			return BackupValidationStatus.Blocked;
		}

		if (!backupExists)
		{
			bool isBackupCreated = await TryCreateBackupAsync(
				validatedFileContents,
				cancellationToken);
			return isBackupCreated
				? BackupValidationStatus.Available
				: BackupValidationStatus.Unavailable;
		}

		string? backupFingerprint = null;

		try
		{
			byte[] backupContents = await ReadSettingsFileAsync(
				BackupFilePath,
				cancellationToken);
			backupFingerprint = ComputeFingerprint(backupContents);
			ParsedSettingsDocument backupDocument = ParseSettingsDocument(backupContents);

			if (backupDocument.SchemaVersion > CurrentSchemaVersion)
			{
				return BackupValidationStatus.FutureVersion;
			}

			if (string.Equals(
				backupFingerprint,
				ComputeFingerprint(validatedFileContents),
				StringComparison.Ordinal))
			{
				return BackupValidationStatus.Available;
			}

			bool isBackupRepaired = await TryReplaceBackupAsync(
				validatedFileContents,
				backupFingerprint,
				preserveReplacedBackup: false,
				cancellationToken);
			return isBackupRepaired
				? BackupValidationStatus.Available
				: BackupValidationStatus.Unavailable;
		}
		catch (OperationCanceledException)
		{
			throw;
		}
		catch (SettingsFileTooLargeException)
		{
			return BackupValidationStatus.Oversized;
		}
		catch (Exception exception) when (
			(exception is JsonException) ||
			(exception is InvalidDataException) ||
			(exception is NotSupportedException))
		{
			bool isBackupRepaired = await TryReplaceBackupAsync(
				validatedFileContents,
				backupFingerprint,
				preserveReplacedBackup: true,
				cancellationToken);
			return isBackupRepaired
				? BackupValidationStatus.Available
				: BackupValidationStatus.Unavailable;
		}
		catch (Exception exception) when (
			(exception is IOException) ||
			(exception is UnauthorizedAccessException))
		{
			return BackupValidationStatus.Unavailable;
		}
	}

	private async Task<bool> TryReplaceBackupAsync(
		byte[] validatedFileContents,
		string? expectedBackupFingerprint,
		bool preserveReplacedBackup,
		CancellationToken cancellationToken)
	{
		if (expectedBackupFingerprint is null)
		{
			return false;
		}

		string? directory = Path.GetDirectoryName(_filePath);

		if (directory is null)
		{
			return false;
		}

		string temporaryPath = Path.Combine(
			directory,
			$".{Path.GetFileName(BackupFilePath)}.{Guid.NewGuid():N}.repair.tmp");

		try
		{
			if (!await FileExistsAsync(BackupFilePath, cancellationToken)
					.ConfigureAwait(false))
			{
				return await TryCreateBackupAsync(
					validatedFileContents,
					cancellationToken);
			}

			await WriteFileDurablyAsync(
				temporaryPath,
				validatedFileContents,
				cancellationToken).ConfigureAwait(false);
			byte[] currentBackupContents = await ReadSettingsFileAsync(
				BackupFilePath,
				cancellationToken);

			if (!string.Equals(
				ComputeFingerprint(currentBackupContents),
				expectedBackupFingerprint,
				StringComparison.Ordinal))
			{
				return false;
			}

			string? recoveryPath = preserveReplacedBackup
				? CreateRecoveryPath(BackupFilePath)
				: null;
			await Task.Run(
				() => ReplaceFileSafely(
					temporaryPath,
					BackupFilePath,
					recoveryPath),
				CancellationToken.None).ConfigureAwait(false);
			return true;
		}
		catch (OperationCanceledException)
		{
			throw;
		}
		catch (Exception exception) when (
			(exception is IOException) ||
			(exception is UnauthorizedAccessException) ||
			(exception is InvalidDataException) ||
			(exception is NotSupportedException))
		{
			return false;
		}
		finally
		{
			await TryDeleteTemporaryFileAsync(temporaryPath).ConfigureAwait(false);
		}
	}

	private async Task<bool> TryCreateBackupAsync(
		byte[] validatedFileContents,
		CancellationToken cancellationToken)
	{
		if (await FileExistsAsync(BackupFilePath, cancellationToken)
				.ConfigureAwait(false))
		{
			return false;
		}

		string? directory = Path.GetDirectoryName(_filePath);

		if (directory is null)
		{
			return false;
		}

		string temporaryPath = Path.Combine(
			directory,
			$".{Path.GetFileName(BackupFilePath)}.{Guid.NewGuid():N}.migration.tmp");

		try
		{
			await WriteFileDurablyAsync(
				temporaryPath,
				validatedFileContents,
				cancellationToken).ConfigureAwait(false);

			if (await FileExistsAsync(BackupFilePath, cancellationToken)
					.ConfigureAwait(false))
			{
				return false;
			}

			await Task.Run(
				() => MoveFileSafely(temporaryPath, BackupFilePath),
				CancellationToken.None).ConfigureAwait(false);
			return true;
		}
		catch (OperationCanceledException)
		{
			throw;
		}
		catch (Exception exception) when (
			(exception is IOException) ||
			(exception is UnauthorizedAccessException) ||
			(exception is NotSupportedException))
		{
			return false;
		}
		finally
		{
			await TryDeleteTemporaryFileAsync(temporaryPath).ConfigureAwait(false);
		}
	}

	private async Task<AccountProfileLoadResult> LoadMissingPrimaryAsync(
		CancellationToken cancellationToken)
	{
		if (!await FileExistsAsync(BackupFilePath, cancellationToken)
				.ConfigureAwait(false))
		{
			_isInitialized = true;
			return new AccountProfileLoadResult(
				Array.Empty<AccountProfile>(),
				AccountProfileLoadStatus.Missing,
				CanSave: true);
		}

		string? backupFingerprint = null;

		try
		{
			byte[] backupContents = await ReadSettingsFileAsync(
				BackupFilePath,
				cancellationToken);
			backupFingerprint = ComputeFingerprint(backupContents);
			ParsedSettingsDocument backupDocument = ParseSettingsDocument(backupContents);
			return await RestoreBackupAsync(
				backupContents,
				backupFingerprint,
				backupDocument,
				primaryFingerprint: null,
				cancellationToken);
		}
		catch (OperationCanceledException)
		{
			throw;
		}
		catch (Exception exception) when (
			(exception is JsonException) ||
			(exception is InvalidDataException) ||
			(exception is NotSupportedException))
		{
			return await Task.Run(
				() => RecoverCorruptBackupWithoutPrimary(backupFingerprint),
				cancellationToken).ConfigureAwait(false);
		}
		catch (Exception exception) when (
			(exception is IOException) ||
			(exception is UnauthorizedAccessException))
		{
			string message = "帳號設定檔遺失，也無法讀取備份。為避免覆寫，目前無法編輯帳號。";
			BlockSaving(message);
			_isInitialized = true;
			return new AccountProfileLoadResult(
				Array.Empty<AccountProfile>(),
				AccountProfileLoadStatus.Unavailable,
				CanSave: false,
				message);
		}
	}

	private async Task<AccountProfileLoadResult> RecoverCorruptFileAsync(
		string? expectedFingerprint,
		CancellationToken cancellationToken)
	{
		if (!await FileExistsAsync(BackupFilePath, cancellationToken)
				.ConfigureAwait(false))
		{
			return await Task.Run(
				() => RecoverCorruptFile(
					expectedFingerprint,
					invalidBackupFingerprint: null),
				cancellationToken).ConfigureAwait(false);
		}

		string? backupFingerprint = null;

		try
		{
			byte[] backupContents = await ReadSettingsFileAsync(
				BackupFilePath,
				cancellationToken);
			backupFingerprint = ComputeFingerprint(backupContents);
			ParsedSettingsDocument backupDocument = ParseSettingsDocument(backupContents);
			return await RestoreBackupAsync(
				backupContents,
				backupFingerprint,
				backupDocument,
				expectedFingerprint,
				cancellationToken);
		}
		catch (OperationCanceledException)
		{
			throw;
		}
		catch (Exception exception) when (
			(exception is JsonException) ||
			(exception is InvalidDataException) ||
			(exception is NotSupportedException))
		{
			return await Task.Run(
				() => RecoverCorruptFile(expectedFingerprint, backupFingerprint),
				cancellationToken).ConfigureAwait(false);
		}
		catch (Exception exception) when (
			(exception is IOException) ||
			(exception is UnauthorizedAccessException))
		{
			string message = "帳號設定檔已損壞，也無法讀取備份。為避免覆寫，目前無法編輯帳號。";
			BlockSaving(message);
			_isInitialized = true;
			return new AccountProfileLoadResult(
				Array.Empty<AccountProfile>(),
				AccountProfileLoadStatus.Unavailable,
				CanSave: false,
				message);
		}
	}

	private AccountProfileLoadResult RecoverCorruptFile(
		string? expectedFingerprint,
		string? invalidBackupFingerprint)
	{
		string? directory = Path.GetDirectoryName(_filePath);

		if (directory is null)
		{
			string unavailableMessage = "帳號設定檔路徑無效，目前無法編輯帳號。";
			BlockSaving(unavailableMessage);
			_isInitialized = true;
			return new AccountProfileLoadResult(
				Array.Empty<AccountProfile>(),
				AccountProfileLoadStatus.Unavailable,
				CanSave: false,
				unavailableMessage);
		}

		string recoveryPath = CreateRecoveryPath(_filePath);
		string? backupRecoveryPath = invalidBackupFingerprint is null
			? null
			: CreateRecoveryPath(BackupFilePath);

		try
		{
			if ((expectedFingerprint is null) ||
				!FileExistsSafely(_filePath) ||
				!string.Equals(
					ComputeFingerprint(ReadSettingsFile(_filePath)),
					expectedFingerprint,
					StringComparison.Ordinal))
			{
				string changedMessage = "其他程序在讀取期間修改了帳號設定檔。為避免移動新內容，目前無法編輯帳號。";
				BlockSaving(changedMessage);
				_isInitialized = true;
				return new AccountProfileLoadResult(
					Array.Empty<AccountProfile>(),
					AccountProfileLoadStatus.Unavailable,
					CanSave: false,
					changedMessage);
			}

			if (invalidBackupFingerprint is not null)
			{
				if (!FileExistsSafely(BackupFilePath) ||
					!string.Equals(
						ComputeFingerprint(ReadSettingsFile(BackupFilePath)),
						invalidBackupFingerprint,
						StringComparison.Ordinal))
				{
					string changedMessage = "其他程序在讀取期間修改了帳號設定備份。為避免移動新內容，目前無法編輯帳號。";
					BlockSaving(changedMessage);
					_isInitialized = true;
					return new AccountProfileLoadResult(
						Array.Empty<AccountProfile>(),
						AccountProfileLoadStatus.Unavailable,
						CanSave: false,
						changedMessage);
				}

				MoveFileSafely(BackupFilePath, backupRecoveryPath!);
			}

			MoveFileSafely(_filePath, recoveryPath);
		}
		catch (Exception exception) when (
			(exception is IOException) ||
			(exception is UnauthorizedAccessException) ||
			(exception is InvalidDataException) ||
			(exception is NotSupportedException))
		{
			string unavailableMessage = "帳號設定檔已損壞，也無法保留副本。目前無法編輯帳號。";
			BlockSaving(unavailableMessage);
			_isInitialized = true;
			return new AccountProfileLoadResult(
				Array.Empty<AccountProfile>(),
				AccountProfileLoadStatus.Unavailable,
				CanSave: false,
				unavailableMessage);
		}

		EnableSaving();
		SetLoadedFileState(fileExisted: false, fingerprint: null);
		_isInitialized = true;
		string message = invalidBackupFingerprint is null
			? "帳號設定檔格式無效，已保留原檔並改用空白設定。"
			: "帳號設定檔與備份格式都無效，已保留原檔並改用空白設定。";
		return new AccountProfileLoadResult(
			Array.Empty<AccountProfile>(),
			AccountProfileLoadStatus.RecoveredCorruptFile,
			CanSave: true,
			message,
			recoveryPath);
	}

	private AccountProfileLoadResult RecoverCorruptBackupWithoutPrimary(
		string? expectedFingerprint)
	{
		if (expectedFingerprint is null)
		{
			string unavailableMessage = "帳號設定檔遺失，也無法確認備份內容。目前無法編輯帳號。";
			BlockSaving(unavailableMessage);
			_isInitialized = true;
			return new AccountProfileLoadResult(
				Array.Empty<AccountProfile>(),
				AccountProfileLoadStatus.Unavailable,
				CanSave: false,
				unavailableMessage);
		}

		string recoveryPath = CreateRecoveryPath(BackupFilePath);

		try
		{
			if (!FileExistsSafely(BackupFilePath) ||
				!string.Equals(
					ComputeFingerprint(ReadSettingsFile(BackupFilePath)),
					expectedFingerprint,
					StringComparison.Ordinal))
			{
				string changedMessage = "其他程序在讀取期間修改了帳號設定備份。為避免移動新內容，目前無法編輯帳號。";
				BlockSaving(changedMessage);
				_isInitialized = true;
				return new AccountProfileLoadResult(
					Array.Empty<AccountProfile>(),
					AccountProfileLoadStatus.Unavailable,
					CanSave: false,
					changedMessage);
			}

			MoveFileSafely(BackupFilePath, recoveryPath);
		}
		catch (Exception exception) when (
			(exception is IOException) ||
			(exception is UnauthorizedAccessException) ||
			(exception is InvalidDataException) ||
			(exception is NotSupportedException))
		{
			string unavailableMessage = "帳號設定備份已損壞，也無法保留副本。目前無法編輯帳號。";
			BlockSaving(unavailableMessage);
			_isInitialized = true;
			return new AccountProfileLoadResult(
				Array.Empty<AccountProfile>(),
				AccountProfileLoadStatus.Unavailable,
				CanSave: false,
				unavailableMessage);
		}

		EnableSaving();
		SetLoadedFileState(fileExisted: false, fingerprint: null);
		_isInitialized = true;
		string message = "帳號設定檔遺失且備份格式無效，已保留損壞備份並改用空白設定。";
		return new AccountProfileLoadResult(
			Array.Empty<AccountProfile>(),
			AccountProfileLoadStatus.RecoveredCorruptFile,
			CanSave: true,
			message,
			recoveryPath);
	}

	private async Task<AccountProfileLoadResult> RestoreBackupAsync(
		byte[] backupContents,
		string backupFingerprint,
		ParsedSettingsDocument backupDocument,
		string? primaryFingerprint,
		CancellationToken cancellationToken)
	{
		string? directory = Path.GetDirectoryName(_filePath);

		if (directory is null)
		{
			string unavailableMessage = "帳號設定檔路徑無效，目前無法編輯帳號。";
			BlockSaving(unavailableMessage);
			_isInitialized = true;
			return new AccountProfileLoadResult(
				Array.Empty<AccountProfile>(),
				AccountProfileLoadStatus.Unavailable,
				CanSave: false,
				unavailableMessage);
		}

		string temporaryPath = Path.Combine(
			directory,
			$".{Path.GetFileName(_filePath)}.{Guid.NewGuid():N}.restore.tmp");
		string? recoveryPath = primaryFingerprint is null
			? null
			: CreateRecoveryPath(_filePath);

		try
		{
			bool backupExists = await FileExistsAsync(
				BackupFilePath,
				cancellationToken).ConfigureAwait(false);

			if (!backupExists ||
				!string.Equals(
					ComputeFingerprint(await ReadSettingsFileAsync(
						BackupFilePath,
						cancellationToken)),
					backupFingerprint,
					StringComparison.Ordinal))
			{
				throw new IOException("帳號設定備份在還原期間已變更。");
			}

			bool primaryExists = await FileExistsAsync(
				_filePath,
				cancellationToken).ConfigureAwait(false);

			if (primaryFingerprint is null)
			{
				if (primaryExists)
				{
					throw new IOException("帳號設定檔在還原期間已由其他程序建立。");
				}
			}
			else if (!primaryExists ||
				!string.Equals(
					ComputeFingerprint(await ReadSettingsFileAsync(
						_filePath,
						cancellationToken)),
					primaryFingerprint,
					StringComparison.Ordinal))
			{
				throw new IOException("帳號設定檔在還原期間已變更。");
			}

			await WriteFileDurablyAsync(
				temporaryPath,
				backupContents,
				cancellationToken).ConfigureAwait(false);

			if (primaryFingerprint is null)
			{
				await Task.Run(
					() => MoveFileSafely(temporaryPath, _filePath),
					CancellationToken.None).ConfigureAwait(false);
			}
			else
			{
				await Task.Run(
					() => ReplaceFileSafely(
						temporaryPath,
						_filePath,
						recoveryPath),
					CancellationToken.None).ConfigureAwait(false);
			}
		}
		catch (OperationCanceledException)
		{
			throw;
		}
		catch (Exception exception) when (
			(exception is IOException) ||
			(exception is UnauthorizedAccessException) ||
			(exception is InvalidDataException) ||
			(exception is NotSupportedException))
		{
			string unavailableMessage = "無法從帳號設定備份還原。為避免覆寫，目前無法編輯帳號。";
			BlockSaving(unavailableMessage);
			_isInitialized = true;
			return new AccountProfileLoadResult(
				Array.Empty<AccountProfile>(),
				AccountProfileLoadStatus.Unavailable,
				CanSave: false,
				unavailableMessage);
		}
		finally
		{
			await TryDeleteTemporaryFileAsync(temporaryPath).ConfigureAwait(false);
		}

		SetLoadedFileState(fileExisted: true, fingerprint: backupFingerprint);
		_isInitialized = true;

		if (backupDocument.SchemaVersion > CurrentSchemaVersion)
		{
			string message = "已從備份還原帳號設定，但這份備份由較新版本建立。為避免覆寫，目前無法編輯帳號。";
			BlockSaving(message);
			return new AccountProfileLoadResult(
				Array.Empty<AccountProfile>(),
				AccountProfileLoadStatus.UnsupportedVersion,
				CanSave: false,
				message,
				recoveryPath);
		}

		EnableSaving();
		string recoveredMessage = primaryFingerprint is null
			? "帳號設定檔遺失，已從驗證通過的備份自動還原。"
			: "帳號設定檔已從驗證通過的備份自動還原；原損壞檔已保留。";
		return new AccountProfileLoadResult(
			backupDocument.Accounts!,
			AccountProfileLoadStatus.RecoveredCorruptFile,
			CanSave: true,
			recoveredMessage,
			recoveryPath);
	}

	private static string CreateRecoveryPath(string filePath)
	{
		string directory = Path.GetDirectoryName(filePath)!;
		string fileNameWithoutExtension = Path.GetFileNameWithoutExtension(filePath);
		string extension = Path.GetExtension(filePath);
		return Path.Combine(
			directory,
			$"{fileNameWithoutExtension}.corrupt-{DateTimeOffset.UtcNow:yyyyMMddTHHmmssfffZ}-{Guid.NewGuid():N}{extension}");
	}

	private async Task<string> SaveDocumentAsync(
		SettingsDocument document,
		CancellationToken cancellationToken)
	{
		string? directory = Path.GetDirectoryName(_filePath);

		if (directory is null)
		{
			throw new AccountProfileStoreException("帳號設定檔路徑無效。");
		}

		await CreateDirectoryAsync(directory, cancellationToken)
			.ConfigureAwait(false);
		byte[] serializedDocument = JsonSerializer.SerializeToUtf8Bytes(
			document,
			SerializerOptions);

		if (serializedDocument.Length > MaximumSettingsFileSize)
		{
			throw new AccountProfileStoreException(
				"帳號設定檔超過可儲存的大小上限。");
		}

		string fingerprint = ComputeFingerprint(serializedDocument);
		string temporaryPath = Path.Combine(
			directory,
			$".{Path.GetFileName(_filePath)}.{Guid.NewGuid():N}.tmp");
		string temporaryBackupPath = Path.Combine(
			directory,
			$".{Path.GetFileName(BackupFilePath)}.{Guid.NewGuid():N}.tmp");

		try
		{
			await WriteFileDurablyAsync(
				temporaryPath,
				serializedDocument,
				cancellationToken).ConfigureAwait(false);
			await WriteFileDurablyAsync(
				temporaryBackupPath,
				serializedDocument,
				cancellationToken).ConfigureAwait(false);
			await RecordPortableImportPreparedWriteAsync(
				_filePath,
				temporaryPath,
				cancellationToken).ConfigureAwait(false);

			await Task.Run(
				() =>
				{
					if (FileExistsSafely(_filePath))
					{
						ReplaceFileSafely(
							temporaryPath,
							_filePath,
							destinationBackupFileName: null);
					}
					else
					{
						MoveFileSafely(temporaryPath, _filePath);
					}
				},
				CancellationToken.None).ConfigureAwait(false);

			SetLoadedFileState(fileExisted: true, fingerprint: fingerprint);

			try
			{
				await RecordPortableImportPreparedWriteAsync(
					BackupFilePath,
					temporaryBackupPath,
					cancellationToken).ConfigureAwait(false);
				await Task.Run(
					() =>
					{
						if (FileExistsSafely(BackupFilePath))
						{
							ReplaceFileSafely(
								temporaryBackupPath,
								BackupFilePath,
								destinationBackupFileName: null);
						}
						else
						{
							MoveFileSafely(
								temporaryBackupPath,
								BackupFilePath);
						}
					},
					CancellationToken.None).ConfigureAwait(false);
			}
			catch (Exception exception) when (
				(exception is IOException) ||
				(exception is UnauthorizedAccessException) ||
				(exception is NotSupportedException))
			{
				throw new AccountProfileStoreException(
					"帳號設定已套用，但備份更新失敗。請確認 AI Usage 設定資料夾的寫入權限，然後再次儲存帳號設定。",
					exception,
					hasCommittedChanges: true);
			}
		}
		finally
		{
			await Task.WhenAll(
				TryDeleteTemporaryFileAsync(temporaryPath),
				TryDeleteTemporaryFileAsync(temporaryBackupPath))
				.ConfigureAwait(false);
		}

		return fingerprint;
	}

	private Task RecordPortableImportPreparedWriteAsync(
		string destinationFilePath,
		string preparedFilePath,
		CancellationToken cancellationToken)
	{
		return _portableSettingsImportWriteTracker is null
			? Task.CompletedTask
			: _portableSettingsImportWriteTracker.RecordPreparedWriteAsync(
				destinationFilePath,
				preparedFilePath,
				cancellationToken);
	}

	private void ReportDiagnostic(
		string operation,
		string summary,
		Exception exception)
	{
		try
		{
			_reportDiagnostic(operation, summary, exception);
		}
		catch
		{
			// Diagnostics must never alter a persistence outcome.
		}
	}

	private static void MoveFileSafely(
		string sourceFilePath,
		string destinationFilePath)
	{
		ManagedFilePathGuard.EnsureExistingFilePathIsSafe(
			sourceFilePath,
			ManagedPathDescription);
		ManagedFilePathGuard.EnsureExistingFilePathIsSafe(
			destinationFilePath,
			ManagedPathDescription);
		File.Move(sourceFilePath, destinationFilePath);
	}

	private static void ReplaceFileSafely(
		string sourceFilePath,
		string destinationFilePath,
		string? destinationBackupFileName)
	{
		ManagedFilePathGuard.EnsureExistingFilePathIsSafe(
			sourceFilePath,
			ManagedPathDescription);
		ManagedFilePathGuard.EnsureExistingFilePathIsSafe(
			destinationFilePath,
			ManagedPathDescription);
		if (destinationBackupFileName is not null)
		{
			ManagedFilePathGuard.EnsureExistingFilePathIsSafe(
				destinationBackupFileName,
				ManagedPathDescription);
		}

		File.Replace(
			sourceFilePath,
			destinationFilePath,
			destinationBackupFileName);
	}

	private static Task WriteFileDurablyAsync(
		string filePath,
		byte[] fileContents,
		CancellationToken cancellationToken)
	{
		cancellationToken.ThrowIfCancellationRequested();
		return Task.Run(
			async () =>
			{
				ManagedFilePathGuard.EnsureExistingFilePathIsSafe(
					filePath,
					ManagedPathDescription);
				await using FileStream stream = new(
					filePath,
					FileMode.CreateNew,
					FileAccess.Write,
					FileShare.None,
					bufferSize: 4096,
					FileOptions.Asynchronous | FileOptions.WriteThrough);
				await stream.WriteAsync(fileContents, cancellationToken)
					.ConfigureAwait(false);
				await stream.FlushAsync(cancellationToken).ConfigureAwait(false);
				stream.Flush(flushToDisk: true);
			},
			cancellationToken);
	}

	private static void TryDeleteTemporaryFile(string temporaryPath)
	{
		try
		{
			ManagedFilePathGuard.EnsureExistingFilePathIsSafe(
				temporaryPath,
				ManagedPathDescription);
			File.Delete(temporaryPath);
		}
		catch (Exception exception) when (
			(exception is IOException) ||
			(exception is UnauthorizedAccessException) ||
			(exception is NotSupportedException))
		{
			// Best effort cleanup. The uniquely named temp file is never loaded as settings.
		}
	}

	private static Task TryDeleteTemporaryFileAsync(string temporaryPath)
	{
		return Task.Run(
			() => TryDeleteTemporaryFile(temporaryPath),
			CancellationToken.None);
	}

	private async Task VerifyFileHasNotChangedAsync(CancellationToken cancellationToken)
	{
		bool fileExists = await FileExistsAsync(_filePath, cancellationToken)
			.ConfigureAwait(false);

		if (fileExists != _loadedFileExisted)
		{
			throw new AccountProfileStoreException(
				"帳號設定檔已由其他程序變更；請重新啟動應用程式後再操作。");
		}

		if (!fileExists)
		{
			return;
		}

		byte[] currentFileContents = await ReadSettingsFileAsync(
			_filePath,
			cancellationToken);
		string currentFingerprint = ComputeFingerprint(currentFileContents);

		if (!string.Equals(
			currentFingerprint,
			_loadedFileFingerprint,
			StringComparison.Ordinal))
		{
			throw new AccountProfileStoreException(
				"帳號設定檔已由其他程序變更；請重新啟動應用程式後再操作。");
		}
	}

	private async Task VerifyBackupCanBeReplacedAsync(
		CancellationToken cancellationToken)
	{
		if (!await FileExistsAsync(BackupFilePath, cancellationToken)
				.ConfigureAwait(false))
		{
			return;
		}

		try
		{
			byte[] backupContents = await ReadSettingsFileAsync(
				BackupFilePath,
				cancellationToken);
			ParsedSettingsDocument backupDocument = ParseSettingsDocument(backupContents);

			if (backupDocument.SchemaVersion > CurrentSchemaVersion)
			{
				throw new AccountProfileStoreException(
					"帳號設定備份由較新版本建立；為避免覆寫，請使用建立該備份的版本。");
			}
		}
		catch (OperationCanceledException)
		{
			throw;
		}
		catch (AccountProfileStoreException)
		{
			throw;
		}
		catch (Exception exception) when (
			(exception is JsonException) ||
			(exception is InvalidDataException) ||
			(exception is NotSupportedException))
		{
			// An invalid backup is not last-known-good and may be replaced by this valid save.
		}
	}

	private void BlockSaving(string message)
	{
		_canSave = false;
		_saveBlockedMessage = message;
	}

	private void EnableSaving()
	{
		_canSave = true;
		_saveBlockedMessage = null;
	}

	private void SetLoadedFileState(bool fileExisted, string? fingerprint)
	{
		_loadedFileExisted = fileExisted;
		_loadedFileFingerprint = fingerprint;
	}
}
